<?php 

$articles = [
array(name => "Faith Shearin MFA '93",
	text => "<p><strong>Faith Shearin MFA '93</strong> announces that her fifth book of poems, <a href=\"http://www.thebroadkillriverpress.com/apps/webstore/products/show/6552450\" target=\"_blank\"><em>Orpheus,</em> <em>Turning</em></a>, won the Dogfish Head Poetry Prize and was published by Broadkill River Press in December.</p>",
	url => "http://www.thebroadkillriverpress.com/apps/webstore/products/show/6552450",
	date => "March 16, 2016"),
array(name => "John Powell '09",
	text => "<p><strong>John Powell '09</strong> announces that his first children's book, <em>The Pitkin Kids Learn About Recycling</em>, has been published through Young Street Publishing. The book is about a group of environmentalist kids who visit a recycling center to learn what happens to recycling after you put it in your bin. The book is meant to also inform adults so that families can become stewards of their environment. You can get it on <a href=\"http://www.amazon.com/Pitkin-Kids-Learn-About-Recycling/dp/0692626298/ref=sr_1_1?ie=UTF8&amp;qid=1457378807&amp;sr=8-1&amp;keywords=The+Pitkin+Kids+Learn+About+Recycling\" target=\"_blank\">Amazon</a> or ask your local bookseller to stock a copy or two!</p>",
	url => "http://www.amazon.com/Pitkin-Kids-Learn-About-Recycling/dp/0692626298/ref=sr_1_1?ie=UTF8&amp;qid=1457378807&amp;sr=8-1&amp;keywords=The+Pitkin+Kids+Learn+About+Recycling",
	date => "March 16, 2016"),
array(name => "Alysson Light '07",
	text => "<p><strong>Alysson Light '07</strong> recently accepted a position as an Assistant Professor of Psychology at the University of the Sciences in Philadelphia. “I'll be starting in the Fall, and looking forward to connecting with other alumni in Philly!”</p>",
	date => "March 16, 2016"),
array(name => "Bianca Rose Ambrosio MFA ‘14",
	text => "<p><strong>Bianca Rose Ambrosio MFA ‘14</strong> announces that her play <em>Gracey</em> was selected to premiere at <a href=\"http://manhattanrep.com/\" target=\"_blank\">Manhattan Repertory Theatre</a>'s Spring Play Competition. The competition will run from March 16-19 at 6:30 pm, and possibly go onto finals which will take place on March 31st at 6:30 and 9:00 pm, as well as April 1st at the same times.</p>",
	url => "http://manhattanrep.com/",
	date => "March 16, 2016"),
array(name => "Ariel Dougherty '69",
	text => "<p><strong>Ariel Dougherty '69</strong> announces that her film <em>Sweet Bananas</em> will be screened in Albuquerque at <a href=\"http://www.experimentsincinema.org/\" target=\"_blank\">Experiments in Cinema</a> on April 6, 5:30 p.m. at the Guild Cinema. The film also features two alumni, <strong>Ann Taylor '69</strong> and <strong>Gina Gilmour '71</strong> as well as Weba Garretson, younger sister of Julie <strong>Garretson Strand '66</strong>.</p>",
	url => "http://www.experimentsincinema.org/",
	date => "March 16, 2016"),
array(name => "Ian Spencer Bell '13",
	text => "<p><strong>Ian Spencer Bell '13</strong> will be dancing a new solo with poems, <em>Marrow</em>, at the Bureau of General Services—Queer Division (The Center, 208 West 13th Street, Room 101, New York City) on Thursday, March 17 and Friday, March 18 at 8 pm. There is a $15 suggested donation, with proceeds supporting The Center's youth programs and BGSQD. For more information on upcoming performances, visit <a href=\"http://www.ianspencerbell.com/\" target=\"_blank\">his website</a>.</p>",
	url => "http://www.ianspencerbell.com/",
	date => "February 23, 2016"),
array(name => "Jenna Esposito ‘00",
	text => "<p><strong>Jenna Esposito ‘00</strong> is delighted to announce that she is teaming up with NYC nightlife favorite Bill Zeffiro, for an open-ended run at Restaurant Row's La Rivista (313 W 46th St, New York). They'll be there every Wednesday from 8 pm – midnight singing standards, pop, Italian songs, and whatever else pops into their heads! Check <a href=\"http://www.jennaesposito.com/shows.html\" target=\"_blank\">her website</a> for all upcoming shows.</p>",
	url => "http://www.jennaesposito.com/shows.html",
	date => "February 23, 2016"),
array(name => "Lisa Rhodes-Ryabchich MFA '99",
	text => "<p><strong>Lisa Rhodes-Ryabchich MFA '99</strong> announces the that her first poetry chapbook entitled <em>We Are Beautiful Like Snowflakes</em> is now available for pre-order sales. It is being published by <a href=\"https://finishinglinepress.com/product_info.php?cPath=2&amp;products_id=2612\" target=\"_blank\">Finishing Line Press</a>.</p>",
	url => "https://finishinglinepress.com/product_info.php?cPath=2&amp;products_id=2612",
	date => "February 23, 2016"),
array(name => "Jean Erdman '38",
	text => "<p>The Earle Ernst Lab Theatre recently held a retrospective celebration of the Aloha Legacy of Dance of <strong>Jean Erdman '38</strong>. Dancers, musicians, friends, and other professional associates gathered to celebrate her distinguished career on her 100th birthday.</p>",
	date => "February 23, 2016"),
array(name => "Erik Hammerstrom '97",
	text => "<p><strong>Erik Hammerstrom '97</strong> published his first book, <a href=\"http://cup.columbia.edu/book/the-science-of-chinese-buddhism/9780231170345\" target=\"_blank\"><em>The Science of Chinese Buddhism: Early Twentieth-Century Engagements</em></a>, with Columbia University Press in August 2015. Examining dozens of previously unstudied writings from the Chinese Buddhist press, this book maps Buddhists' efforts to rethink their traditions through science in the initial decades of the twentieth century. Showcasing the rich and progressive steps Chinese religious scholars took in adapting to science's rising authority, this volume offers a key perspective on how a major Eastern power transitioned to modernity in the twentieth century and how its intellectuals anticipated many of the ideas debated by scholars of science and Buddhism today.</p>",
	url => "http://cup.columbia.edu/book/the-science-of-chinese-buddhism/9780231170345",
	date => "February 18, 2016"),
array(name => "Janet Dephoure '60",
	text => "<p><strong>Janet Dephoure '60</strong> Just began a new job as a senior technical writer at Digital Guardian, a computer security company in Waltham, Massachusetts.</p>",
	date => "February 18, 2016"),
array(name => "Jay Strong '78",
	text => "<p><strong>Jay Strong '78</strong> invites alumni to another reading of his play, <em>The Demi-Orphans</em>, February 21 at 6 pm at <a href=\"https://www.workshoptheater.org/workshop-events/2016/2/21/the-demi-orphans\" target=\"_blank\">Workshop Theater</a> (312 West 36th Street) in New York.</p>",
	url => "https://www.workshoptheater.org/workshop-events/2016/2/21/the-demi-orphans",
	date => "February 18, 2016"),
array(name => "Eric John Meyer MFA '09",
	text => "<p><strong>Eric John Meyer MFA '09</strong> announces the opening of his play, <em>Due to Events</em>, by Human Head Performance Group at The Brick (575 Metropolitan Avenue, Brooklyn) on February 5 at 8 pm. <em>Due to Events</em> tells the story of Hero, a woman under house arrest, and her lawyer who travels the world trying to find information that will set her free. The show runs until February 27, go to <a href=\"http://www.duetoevents.com/\" target=\"_blank\">the website</a> to find tickets.</p>",
	url => "http://www.duetoevents.com/",
	date => "February 5, 2016"),
array(name => "Erica NewHouse '03",
	text => "<p><strong>Erica NewHouse '03</strong> will be teaching a new six-week acting workshop in New York City beginning Sunday, February 7 from 4 to 6 pm at Larry Singer Studios (118-122 Baxter St, Suite 403). To sign up or to get more information, call 917-327-5406.</p>",
	date => "February 5, 2016"),
array(name => "Annie Lanzillotto MFA '90",
	text => "<p><strong>Annie Lanzillotto MFA '90</strong> invites alumni to attend the launch of her audiobook \"L is for Lion\" Saturday, February 13 from 6 to 9 pm at CityLore (59 East 1<sup>st</sup> St, New York).&nbsp; “Beads, masks, libations, antics…Mardi Gras and San Valentino energies abound. Have a listen: http://tiny.cc/kikk8x</p>",
	date => "February 5, 2016"),
array(name => "Lisa Rybovich Cralle '04",
	text => "<p><strong>Lisa Rybovich Cralle '04</strong> and Sophia Wang will be taking over <a href=\"http://www.interfaceartgallery.com/\" target=\"_blank\">Interface Gallery</a> (486 49<sup>th</sup> St, Oakland) from February 14-28, constructing an immersive installation as part of their “Bodily Engagements” series. See the gallery's website for performance times. Cralle will also be participating in a group show, “Unstable Labor” at Syracuse University February 12. “<a href=\"http://www.adlerandedmark.com/\" target=\"_blank\">Adler &amp; Edmark</a> have invited a group of artists to submit instructions for artworks that will be made on site by the curators (who are also artists) during their residency at Sculpture Space.”</p>",
	url => "http://www.interfaceartgallery.com/",
	date => "February 5, 2016"),
array(name => "Kristin Leong '03",
	text => "<p><strong>Kristin Leong '03</strong> spoke at <a href=\"http://www.seattletimes.com/education-lab/watch-our-ignite-education-lab-speakers-present-their-inspiring-stories-about-education/\" target=\"_blank\">Ignite Education Lab</a>, a talk on education featuring 11 speakers. She teaches middle-school humanities at the International School in Bellevue. Follow her on Twitter <a href=\"https://twitter.com/kristinleong\" target=\"_blank\">@kristinleong</a> and connect with her on LinkedIn.</p>",
	url => "http://www.seattletimes.com/education-lab/watch-our-ignite-education-lab-speakers-present-their-inspiring-stories-about-education/",
	date => "February 5, 2016"),
array(name => "Connie Calloway '71",
	text => "<p><strong>Connie Calloway '71</strong> announces that her book, <em><a href=\"http://100piecesofsun.com/\" target=\"_blank\"><em>100 Pieces of Sun, Diary of a Potted Plant</em></a></em>, was published in January. In it, Calloway traces her roots from Alabama to her time at Sarah Lawrence.</p>",
	url => "http://100piecesofsun.com/",
	date => "February 5, 2016"),
array(name => "Stuart Diamond MFA '73",
	text => "<p><em>Master of the Astral Plane</em>, the 1982 opera by <strong>Stuart Diamond MFA '73</strong>, will be broadcast on <a href=\"http://www.wbai.org/\" target=\"_blank\">WBAI 99.5</a> as part of Ear Massage with Mark Laiosa Sunday, January 17<sup>th</sup> at 3 a.m. The program is in honor of the great voice of classical music Harry Fleetwood and the opera itself is a tribute to Fleetwood as it incorporates his narration into the storyline. “For those who would rather not wake up in the middle of the night to listen, you can catch the opera here: <a href=\"http://masteroftheastralplane.synthasite.com/\" target=\"_blank\">Master of the Astral Plane</a>.”</p>",
	url => "http://www.wbai.org/",
	date => "January 14, 2016"),
array(name => "Nina Gibans '54",
	text => "<p><a href=\"http://wviz.ideastream.org/\" target=\"_blank\">WVIZ ideastream</a> public broadcasting will be airing a film by <strong>Nina Gibans '54</strong> on January 31. <a href=\"http://www.universitycirclefilm.com/\" target=\"_blank\"><em>University Circle: Creating A Sense of Place</em></a> is a comprehensive look at the history and resurgence of Cleveland's University Circle neighborhood.</p>",
	url => "http://wviz.ideastream.org/",
	date => "January 14, 2016"),
array(name => "Emily Gropp Carlson '03",
	text => "<p><img alt=\"Symphony No. 2 book cover\" class=\"right\" height=\"74\" src=\"/media/alumni/symphony_no_2.jpg\" width=\"75\">Argos Books published a chapbook of poems by <strong>Emily Gropp Carlson '03</strong>, <a href=\"http://argosbooks.org/?p=2455\" target=\"_blank\"><em>Symphony No. 2</em></a> in fall 2015. Carlson mentions “the great SLC poetry teacher” Suzanne Gardinier in the opening poem.</p>",
	url => "http://argosbooks.org/?p=2455",
	date => "January 14, 2016"),
array(name => "Patricia Dunn MFA '98",
	text => "<p><em>Rebels By Accident</em> by <strong>Patricia Dunn MFA '98</strong> received honorable mention for the <a href=\"http://antiquitynow.org/2016/01/07/top-picks-named-for-2015-children-and-young-adult-books-on-middle-east/\" target=\"_blank\">Middle East Outreach Council 2015 Children and Young Adult Books on Middle East Awards</a>.</p>",
	url => "http://antiquitynow.org/2016/01/07/top-picks-named-for-2015-children-and-young-adult-books-on-middle-east/",
	date => "January 14, 2016"),
array(name => "Joy Ladin '82",
	text => "<p><strong>Joy Ladin '82</strong> is excited to finally share the link to <a href=\"https://www.youtube.com/watch?v=g0K2YvvQyEw\" target=\"_blank\">\"Ain't I a Woman?\"</a>, the TEDxBeaconStreet talk she gave in November.</p>",
	url => "https://www.youtube.com/watch?v=g0K2YvvQyEw",
	date => "January 14, 2016"),
array(name => "Beth Hahn MFA '00",
	text => "<p><strong><img alt=\"The Singing Bone book cover\" class=\"right\" height=\"74\" src=\"/media/alumni/singingbone.jpg\" width=\"50\">Beth Hahn MFA '00</strong> announces that her book, <a href=\"http://shop.reganarts.com/products/the-singing-bone-by-beth-hahn\" target=\"_blank\"><em>The Singing Bone</em></a>, will be published by Regan Arts in March 2016.</p>",
	url => "http://shop.reganarts.com/products/the-singing-bone-by-beth-hahn",
	date => "January 14, 2016"),
array(name => "Gloria Norris '77",
	text => "<p><a href=\"http://shop.reganarts.com/products/kookooland-by-gloria-norris\" target=\"_blank\"><em><img alt=\"KooKooLand book cover\" class=\"right\" height=\"75\" src=\"/media/alumni/kookooland.jpg\" width=\"50\">KooKooLand</em></a>, by <strong>Gloria Norris '77</strong>, was published by Regan Arts. In the true crime memoir, Norris tells the story of growing up in Manchester, New Hampshire with her “charismatic yet cruel” father.</p>",
	url => "http://shop.reganarts.com/products/kookooland-by-gloria-norris",
	date => "January 14, 2016"),
array(name => "Leah Umansky MFA '04",
	text => "<p><strong>Leah Umansky MFA '04</strong> has a new dystopian-themed chapbook of poems forthcoming from Kattywompus Press, <em>Straight Away the Emptied World</em>, this February. More information is available at <a href=\"http://leahumansky.com/\" target=\"_blank\">http://leahumansky.com</a>.&nbsp;</p>",
	url => "http://leahumansky.com/",
	date => "January 14, 2016"),
array(name => "Justin Okin '03",
	text => "<p><strong>Justin Okin '03</strong> will be performing in the West Coast Premiere of Samuel Hunter's <em>Pocotello</em> presented by the award-winning <a href=\"http://roguemachinetheatre.com/show-info/pocatello/\" target=\"_blank\">Rogue Machine Theatre Company</a>, opening February 13. The cast includes Eden Brolin, Anne Gee Byrd, Matthew Elkins, and Tracie Lockwood. Eddie manages an Italian chain restaurant in Pocatello—a small, unexceptional American city that is slowly being paved over with strip malls and franchises. But he can't serve enough Soup, Salad &amp; Breadstick Specials to make his hometown feel like home. Against the harsh backdrop of Hunter's Idaho, this heartbreaking comedy is a cry for connection in an increasingly lonely American landscape.</p>",
	url => "http://roguemachinetheatre.com/show-info/pocatello/",
	date => "January 14, 2016"),
array(name => "Jim Melillo '72",
	text => "<p><strong>Jim Melillo '72</strong> announces the unveiling of the first wine offerings from Melillo and winemaker Jerry Van Vort. “We will be pouring our 2015 whites as well as our 2014 reds after two years in oak. We have brought Santa Barbara quality wines to the east coast and invite all of our fellow wine snobs and winos to come and be amazed.” The tasting will be held March 10 at <a href=\"http://www.priam-vineyards.com/\" target=\"_blank\">Priam Vineyards</a> (11 Shailor Hill Road, Colchester, Connecticut 06415).</p>",
	url => "http://www.priam-vineyards.com/",
	date => "January 14, 2016"),
array(name => "Leslie McGuirk '82",
	text => "<p><strong>Leslie McGuirk '82</strong> has launched her latest project,&nbsp;<a href=\"http://quirkyville.com/\" target=\"_blank\">Quirkyville</a>, an imaginary sea world inhabited by quirky sea creatures. “They deal with the same feelings and issues we humans face everyday. Their positive messages inspire us to be ourselves. Each of these creatures teach us that when you take the time to look below the surface, it's cool to be quirky.”</p>",
	url => "http://quirkyville.com/",
	date => "January 14, 2016"),
array(name => "Jay Strong '78",
	text => "<p><strong>Jay Strong '78</strong> invites alumni to join the next SLC Playwrights Workshop on Sunday, January 10 at 6 p.m. If you'd like to be a part of this exciting opportunity to read, present, and develop new works by up and coming playwrights, please contact <a href=\"mailto:slcnymetro@yahoo.com\">slcnymetro@yahoo.com</a> to join their mailing list.</p>",
	date => "January 7, 2016"),
array(name => "Jane Freeman '71",
	text => "<p><strong><img alt=\"Artwork by Jane Freeman\" class=\"right\" height=\"109\" src=\"/media/alumni/freeman_enews.jpg\" width=\"74\">Jane Freeman '71</strong> will be showing her work with Bix Lye and Dee Shapiro in a show at <a href=\"http://www.art101brooklyn.com/home.html\" target=\"_blank\">Art 101</a> in Williamsburg, Brooklyn. Art 101 was founded in 2004 by <strong>Ellen Rand '62</strong>. The exhibition, which features Freeman's small watercolors and gouaches, opens January 8 with a reception from 6-9 p.m. and runs through February 14. View more of Freeman's work at <a href=\"http://www.janefreemanart.com/\" target=\"_blank\">janefreemanart.com</a>.</p>",
	url => "http://www.art101brooklyn.com/home.html",
	date => "January 7, 2016"),
array(name => "Pepper Fajans '07",
	text => "<p><strong>Pepper Fajans '07</strong> and <strong>Kay Ottinger '10</strong> were recently featured in <a href=\"http://www.nytimes.com/2015/12/06/arts/dance/pepper-fajans-makes-brooklyn-studios-for-dance-a-blessed-refuge.html?contentCollection=weekendreads&amp;action=click&amp;pgtype=Homepage&amp;clickSource=story-heading&amp;module=c-column-middle-span-region%C2%AEion=c-column-middle-span-region&amp;WT.nav=c-column-middle-span-region&amp;_r=1&amp;action=click&amp;pgtype=Homepage&amp;clickSource=story-heading&amp;module=c-column-middle-span-region&amp;region=c-column-middle-span-region&amp;WT.nav=c-column-middle-span-region&amp;_r=0%3E\" target=\"_blank\"><em>The New York Times</em></a> for their work with the <a href=\"http://bksd.org/\" target=\"_blank\">Brooklyn Studios for Dance</a>, “a space devoted to the pedagogy and practice of dance that opened in May in the gymnasium of Cadman Congregational Church.”</p>",
	url => "http://bksd.org/",
	date => "January 7, 2016"),
array(name => "Annie Novak '05",
	text => "<p><strong><img alt=\"The Rooftop Growing Guide book cover\" class=\"right\" height=\"94\" src=\"/media/alumni/rooftop_enews.jpg\" width=\"74\">Annie Novak '05</strong> announces the upcoming release of her book for urban gardeners, <a href=\"http://www.penguinrandomhouse.com/books/239618/the-rooftop-growing-guide-by-annie-novak/9781607747086/\" target=\"_blank\"><em>The Rooftop Growing Guide</em></a>, in February.</p>",
	url => "http://www.penguinrandomhouse.com/books/239618/the-rooftop-growing-guide-by-annie-novak/9781607747086/",
	date => "January 7, 2016"),
array(name => "Manissa Maharawal '05",
	text => "<p><strong><img alt=\"When We Fight We Win! book cover\" class=\"right\" height=\"92\" src=\"/media/alumni/when_we_fight_we_win_enews.jpg\" width=\"74\">Manissa Maharawal '05</strong> was interviewed for and featured extensively in a recent publication by Greg Jobin-Leeds. <a href=\"http://thenewpress.com/books/when-we-fight-we-win\" target=\"_blank\"><em>When We Fight, We Win!</em></a> looks at the past decade of activism, from #BlackLivesMatter to Occupy Wall Street.</p>",
	url => "http://thenewpress.com/books/when-we-fight-we-win",
	date => "January 7, 2016"),
array(name => "Elissa Sussman '05",
	text => "<p><strong><img alt=\"Burn book cover\" class=\"right\" height=\"113\" src=\"/media/alumni/burn_enews.jpg\" width=\"74\">Elissa Sussman '05</strong> continues her young adult series with the release of her new novel, <a href=\"http://elissasussman.com/books/burn/\" target=\"_blank\"><em>Burn</em></a>, January 12.</p>",
	url => "http://elissasussman.com/books/burn/",
	date => "January 7, 2016"),
array(name => "Eva Kittay '67",
	text => "<p>This year, <strong>Eva Kittay '67</strong> received an <a href=\"http://www.neh.gov/grants/research/fellowships\" target=\"_blank\">NEH Fellowship</a> and a <a href=\"http://www.gf.org/about/fellowship/\" target=\"_blank\">Guggenheim Fellowship</a> for a book she is writing on the challenges that cognitive disability poses to a number of important philosophical conceptions. She was also elected Vice President of the <a href=\"http://www.apaonline.org/group/eastern\" target=\"_blank\">Eastern Division of the American Philosophical Association</a>, automatically becoming President next year.</p>",
	url => "http://www.neh.gov/grants/research/fellowships",
	date => "January 7, 2016"),
array(name => "Erin Boyle '06",
	text => "<p><strong><img alt=\"Simple Matters book cover\" class=\"right\" height=\"95\" src=\"/media/alumni/simple matters_enews.jpg\" width=\"74\">Erin Boyle '06</strong> will have her first book, <a href=\"http://www.abramsbooks.com/product/simple-matters_9781419718632/\" target=\"_blank\"><em>Simple Matters</em></a>, published by Abrams Books on January 12, 2016. Boyle shares her philosophy of small-space living and conscious consumption—values she developed living with her husband in a 240-square foot apartment for three years.</p>",
	url => "http://www.abramsbooks.com/product/simple-matters_9781419718632/",
	date => "January 7, 2016"),
array(name => "Stephanie Brody '76",
	text => "<p><strong>Stephanie Brody '76</strong> is pleased to announce the release of her book <a href=\"https://www.routledge.com/products/9781138795273\" target=\"_blank\"><em>Entering Night Country</em></a>, published by Routledge as part of the \"Psychoanalysis in a New Key\" book series.</p>",
	url => "https://www.routledge.com/products/9781138795273",
	date => "January 7, 2016"),
array(name => "Diane Cantor '76",
	text => "<p><strong><img alt=\"The Poisoned Table book cover\" class=\"right\" height=\"112\" src=\"/media/alumni/The Poisoned Table Book Cover_enews.jpg\" width=\"74\">Diane Cantor '76</strong> announces the publication of her historical novel <a href=\"http://www.mupress.org/The-Poisoned-Table-P880.aspx\" target=\"_blank\"><em>The Poisoned Table</em></a>. It tells the story of the rivalry between fictional actress Isabel Graves and real-life 19th century stage sensation Fanny Kemble, and also deals with first-person accounts of American slavery and the roles and conditions of women and children in the 19th century.</p>",
	url => "http://www.mupress.org/The-Poisoned-Table-P880.aspx",
	date => "January 7, 2016"),
array(name => "Leah Umansky MFA '04",
	text => "<p><strong>Leah Umansky MFA '04</strong> will have a new dystopian/sci-fi poetry chapbook out in Spring 2016 with Kattywompus Press called S<em>traight Away the Emptied World</em>.</p>",
	date => "December 2, 2015"),
array(name => "Elissaveta Iordanova MFA '00, MS '15",
	text => "<p><strong>Elissaveta Iordanova MFA '00, MS '15</strong>, an Artistic Director and choreographer of <a href=\"http://www.facebook.com/GORANADANCE\" target=\"_blank\">GORANA DANCE</a> -Bulgarian folk dance collective, announces the 10<sup>th</sup> Anniversary of the company making. \"Rhythms &amp; Patterns\" is a performance, which will be presented on April 2, 2016 at 7 p.m. at JCC Manhattan and commemorate the celebration. All are welcome!</p>",
	url => "http://www.facebook.com/GORANADANCE",
	date => "December 2, 2015"),
array(name => "Mike Levine '07",
	text => "<p><img alt=\"Oh, the Flesh You Will Eat! book cover\" class=\"right\" height=\"113\" src=\"/media/alumni/oh-the-flesh-cover.jpg\" width=\"75\">A highly infectious collection of Dr. Seuss spoofs, <em><a href=\"http://devastatorpress.com/ohtheflesh/\" target=\"_blank\">Oh, the Flesh You Will Eat!</a></em> By Dr. Vireuss (aka <strong>Mike Levine '07</strong>) has been released in hardback. There's the tale of a man who would not—could not!—let a doctor save his life, a sick boy who puts healthy people into quarantine, and a little flesh-eating virus who goes on a big adventure.</p>",
	url => "http://devastatorpress.com/ohtheflesh/",
	date => "December 2, 2015"),
array(name => "Ashley Beldon-Egbuna '98",
	text => "<p><strong>Ashley Beldon-Egbuna '98</strong> invites everyone to check out her Pilates mat videos on her website, <a href=\"https://movetothrive.com/\" target=\"_blank\">Move to Thrive</a>.</p>",
	url => "https://movetothrive.com/",
	date => "December 2, 2015"),
array(name => "Leslie Feinberg '07",
	text => "<p><strong><img alt=\"Prohibition Bakery book cover\" class=\"right\" height=\"113\" src=\"/media/alumni/prohibition_bakery.jpg\" width=\"75\">Leslie Feinberg '07</strong> opened Prohibition Bakery in New York City in 2012, and this fall published a cookbook of the same name. <a href=\"http://www.prohibitionbakery.com/our-book/\" target=\"_blank\"><em>Prohibition Bakery</em></a> includes more than 50 recipes for boozy mini cupcakes adapted for the home cook.</p>",
	url => "http://www.prohibitionbakery.com/our-book/",
	date => "December 2, 2015"),
array(name => "Virginia Pye MFA '87",
	text => "<p><strong><img alt=\"Dreams of the Red Phoenix book cover\" class=\"right\" height=\"108\" src=\"/media/alumni/pye_phoenix.jpg\" width=\"75\">Virginia Pye MFA '87</strong> published her second novel, <em>Dreams of the Red Phoenix</em>, in October. The novel is set in the summer of 1937 in North China, taking her grandmother's life as inspiration.</p>",
	date => "December 2, 2015"),
array(name => "Maggie Kneip MFA '81",
	text => "<p><strong>Maggie Kneip MFA '81</strong> recently published her memoir <a href=\"http://maggiekneip.com/about-the-book/\" target=\"_blank\"><em>Now Everyone Will Know: The Perfect Husband, His Shattering Secret, My Rediscovered Life</em></a>, which was highlighted in the <a href=\"http://nypost.com/2015/11/18/be-brave-brooke-mueller-i-found-out-my-husband-had-hiv-too/\" target=\"_blank\"><em>New York Post</em></a>.</p>",
	url => "http://maggiekneip.com/about-the-book/",
	date => "December 2, 2015"),
array(name => "Judith Silverman '77",
	text => "<p><strong>Judith Silverman '77</strong>&nbsp;was recently featured on <em>PBS</em> television, along with her award-winning film,&nbsp;<em>The Hidden Face of Suicide</em>. Watch the interview with Judith on&nbsp;<a href=\"http://www.youtube.com/watch?v=LFAOnut9B-I\" target=\"_blank\">Youtube</a>. For more information on&nbsp;<em>The Hidden Face of Suicide</em>&nbsp;and Judith's other works, please see:&nbsp;<a href=\"http://www.yehuditsilverman.com/\" target=\"_blank\">http://www.yehuditsilverman.com/</a> <a href=\"http://www.yehuditsilverman.com/\" target=\"_blank\"></a></p>",
	url => "http://www.youtube.com/watch?v=LFAOnut9B-I",
	date => "October 22, 2015"),
array(name => "Margo Stever MFA '88",
	text => "<p><strong>Margo Stever MFA '88</strong>&nbsp;announced the publication of the book,&nbsp;<em>Looking East: William Howard Taft and the 1905 U.S.Diplomatic Mission to Asia</em>, that she co-authored with her son, James Taft Stever. The book was first published by Zhejiang University Press in 2012 and then through a collaboration of the University of Cincinnati and Zhejiang University Press in 2015.&nbsp;<em>Looking East</em>&nbsp;documents a historic trip led by William Howard Taft during his tenure as secretary of war during Theodore Roosevelt's administration.</p>",
	date => "October 22, 2015"),
array(name => "Robert Danberg '96",
	text => "<p><em>Teaching Writing While Standing on One Foot</em>, by&nbsp;<strong>Robert Danberg '96,</strong>&nbsp;was published by Sense Publishers in June 2015. A work of creative nonfiction bends genres such as the lyric essay, instructional manuals, midrash and self-help. It invites readers to meditate on their own lives as learners and teachers, alongside their reading to create a commentary of their own on the essential uncertainty of teaching what must be learned from experience.</p>",
	date => "October 22, 2015"),
array(name => "Ellen Perecman ‘75",
	text => "<p>New Worlds Theatre Project will present the world premiere of David Pinski's comic tragedy,&nbsp;<em>Professor Brenner</em>, in a translation by&nbsp;<strong>Ellen Perecman ‘75</strong>, beginning Sunday, November 1 at 2pm at 145 Sixth Avenue.&nbsp;<a href=\"http://www.broadwayworld.com/article/New-Worlds-Theatre-Project-to-Stage-World-Premiere-of-Pinskis-PROFESSOR-BRENNER-20151012\" target=\"_blank\">See more information here</a>.</p>",
	url => "http://www.broadwayworld.com/article/New-Worlds-Theatre-Project-to-Stage-World-Premiere-of-Pinskis-PROFESSOR-BRENNER-20151012",
	date => "October 22, 2015"),
array(name => "Jay Strong '78",
	text => "<p><strong>Jay Strong '78</strong>&nbsp;announced that November 8 is the NEXT SLC Playwriting Workshop. Attention Playwrights and Screenwriters: Need a fresh perspective? Have all or part of your current work in progress read by professional actors, then supportively discussed in a relaxed atmosphere at the SLC Playwriting Workshop. SLCPW is a FREE informal writing development group, we meet second Sunday of every month at 6pm. Our next meeting is Sunday, November 8. If you'd like to participate, contact&nbsp;<a href=\"mailto:SLCNYMetro@yahoo.com\">SLCNYMetro@yahoo.com<br></a> <a href=\"mailto:SLCNYMetro@yahoo.com\"></a></p>",
	date => "October 22, 2015"),
array(name => "Mike Soto MFA '09",
	text => "<p><strong>Mike Soto MFA '09</strong>&nbsp;announced his nomination for the 2015 Best of Net Anthology, for his poem,&nbsp;<em>When the firing squad lined up, honey</em>originally published in&nbsp;<em>Radar Poetry</em>. See more information on&nbsp;<a href=\"http://www.radarpoetry.com/when-the-firing-squad-lined-up-honey/\" target=\"_blank\">Radar Poetry's web site</a>.</p>",
	url => "http://www.radarpoetry.com/when-the-firing-squad-lined-up-honey/",
	date => "October 22, 2015"),
array(name => "Georgia Lee Hussey '01",
	text => "<p><strong>Georgia Lee Hussey '01</strong>&nbsp;announced that she recently launched Modernist Financial. She wishes to educate and empower creative thinkers through financial planning and asset management. Learn more at&nbsp;<a href=\"http://www.modernistfinancial.com\" target=\"_blank\">www.modernistfinancial.com<br></a> <a href=\"http://www.modernistfinancial.com/\" target=\"_blank\"></a></p>",
	url => "http://www.modernistfinancial.com",
	date => "October 22, 2015"),
array(name => "Brooke Ciardelli '87",
	text => "<p>The Arthur Miller Society presents the premiere of a Syrian-Muslim interpretation of Arthur Miller's<em>&nbsp;A VIEW FROM THE BRIDGE</em>&nbsp;created and directed by&nbsp;<strong>Brooke Ciardelli '87</strong>&nbsp;on October 17 at the Arthur Miller Centennial. Learn more about Brooke at<a href=\"http://brookeciardelli.com/\" target=\"_blank\">http://brookeciardelli.com</a>/</p>",
	url => "http://brookeciardelli.com/",
	date => "October 15, 2015"),
array(name => "Whitney Biancur '13",
	text => "<p><strong>Whitney Biancur '13</strong>, Associate Producer,&nbsp;announced&nbsp;<em>The Elephant In Every Room I Enter</em>, at La MaMa through October 31. Tickets online at&nbsp;<a href=\"http://lamama.org/\" target=\"_blank\">http://lamama.org</a>.</p>",
	url => "http://lamama.org/",
	date => "October 8, 2015"),
array(name => "Audrey Heimler MS '71",
	text => "<p><strong>Audrey Heimler MS '71</strong>&nbsp;shared with us that in 1991, she wrote an article about an unidentified genetic syndrome, that has since been known as Heimler syndrome. Recently a geneticist identified the gene for Heimler syndrome. He was successful and this report was published in the&nbsp;<em>American Journal of Human Genetics</em>&nbsp;-- so now there is a Heimler syndrome and a gene for Heimler syndrome!</p>",
	date => "October 1, 2015"),
array(name => "Kaui Hart Hemmings MFA '02",
	text => "<p>The new YA novel by <strong>Kaui Hart Hemmings MFA '02</strong>, <em>Juniors</em>, is released by Penguin Putnam today. It is available on <a href=\"http://www.amazon.com/Juniors-Kaui-Hart-Hemmings/dp/0399173609/ref=pd_sim_14_2?ie=UTF8&amp;refRID=0BXREV7RC3APJJKABRAAhttp://\" target=\"_blank\">Amazon</a> and other booksellers.</p>",
	url => "http://www.amazon.com/Juniors-Kaui-Hart-Hemmings/dp/0399173609/ref=pd_sim_14_2?ie=UTF8&amp;refRID=0BXREV7RC3APJJKABRAAhttp://",
	date => "September 22, 2015"),
array(name => "Kate Scelsa '02",
	text => "<p><strong>Kate Scelsa '02</strong> will be promoting the publication of her novel <em>Fans of the Impossible Life</em> with a reading and conversation with fellow YA author Nicola Yoon at the Los Angeles Central Library (630 W. 5th St) on Sunday, September 20 at 3pm.</p>",
	date => "September 18, 2015"),
array(name => "Lynn Gilbert '59",
	text => "<p>Photographer <strong>Lynn Gilbert '59</strong> is blogging for <em>Cornucopia</em> with a series of posts that take us on a journey through Turkish homes. <a href=\"http://www.cornucopia.net/blog/inside-story-bodrum/\" target=\"_blank\">Read them here</a>.</p>",
	url => "http://www.cornucopia.net/blog/inside-story-bodrum/",
	date => "September 17, 2015"),
array(name => "Prilla Smith Brackett '64",
	text => "<p><strong>Prilla Smith Brackett '64</strong> will be featured in two exhibits this fall: <a href=\"http://www.catamountarts.org/exhibitions/main-gallery-exhibit/\" target=\"_blank\"><em>Prilla Smith Brackett: Fractured Vision II</em></a>&nbsp;will be at Catamount Arts (111 Eastern Avenue, St. Johnsbury, Vermont 05819) September 16 through October 25 with an artist reception on Friday, October 2, 5-7 pm. <a href=\"http://13forest.com/exhibit/show-Reveal.shtml\" target=\"_blank\">Reveal: Grace Bentley-Scheck, Prilla Smith Brackett, Nina Wishnok</a> opens at 13 Forest Gallery (167A Massachusetts Avenue, Arlington, MA 02474) on September 19 with an opening reception and print fair 4-6 pm, running through November 13. The 3 artists and 2 others will discuss process October 17, 4-6pm.</p>",
	url => "http://www.catamountarts.org/exhibitions/main-gallery-exhibit/",
	date => "September 17, 2015"),
array(name => "A.M. Homes '85",
	text => "<p><strong>A.M. Homes '85</strong> talks with Salman Rushdie about his first adult novel in six years, <em>Two Years Eight Months and Twenty-Eight Nights</em>, on Wednesday, September 16 at 7:30 at Symphony Space. <a href=\"http://www.symphonyspace.org/event/8840/Literature/thalia-book-club-salman-rushdie-i-two-years-eight-months-and-twenty-eight-nights-i-\" target=\"_blank\">Tickets available online</a>.</p>",
	url => "http://www.symphonyspace.org/event/8840/Literature/thalia-book-club-salman-rushdie-i-two-years-eight-months-and-twenty-eight-nights-i-",
	date => "September 16, 2015"),
array(name => "Nancy Donehower '79",
	text => "<p><strong>Nancy Donehower '79</strong>&nbsp;announced the publication of her book,&nbsp;College Admissions Without the Crazy&nbsp;(Senza Pazzia Press, 2014). The book draws on Nancy's background as a psychologist and thirty years of experience helping students navigate the college admissions process. It helps students understand why they get stuck as they search for, apply to, and ultimately choose a college to attend.</p>",
	date => "September 15, 2015"),
array(name => "Kate Scelsa ‘02",
	text => "<p>Calling all YA fans: Join <strong>Kate Scelsa ‘02</strong> and Mariko Tamaki as they chat about Scelsa's new book, <em>Fans of the Impossible Life</em>. The reading takes place at <a href=\"http://www.booksmith.com/event/kate-scelsa-fans-impossible-life-conversation-mariko-tamaki\" target=\"_blank\">The Booksmith</a> (1644 Haight St.) at 7:30 pm on Tuesday, September 15.</p>",
	url => "http://www.booksmith.com/event/kate-scelsa-fans-impossible-life-conversation-mariko-tamaki",
	date => "September 15, 2015"),
array(name => "Dr. Laurie Nadel's '69",
	text => "<p>Read <em>The Huffington Post</em> article,&nbsp;<a href=\"http://www.huffingtonpost.com/laurie-nadel/pastrami-and-wisdom-dr-wa_b_8068048.html\" target=\"_blank\">\"Pastrami and Wisdom: Dr. Wayne Dyer on 'The Afternoon of Life\"</a>,&nbsp;by&nbsp;<strong>Dr. Laurie Nadel's '69.</strong> </p>",
	url => "http://www.huffingtonpost.com/laurie-nadel/pastrami-and-wisdom-dr-wa_b_8068048.html",
	date => "September 10, 2015"),
array(name => "Brigitte Gouchoe MFA '11",
	text => "<p><strong>Brigitte Gouchoe MFA '11</strong> (aka Brigitte Quinn) has published <a href=\"http://www.amazon.com/Anchored-Brigitte-Quinn-ebook/dp/B00ZSOVSYU\" target=\"_blank\"><em>Anchored</em></a>, a novel based on her experience as a broadcast journalist for 1010 WINS and Fox News.</p>",
	url => "http://www.amazon.com/Anchored-Brigitte-Quinn-ebook/dp/B00ZSOVSYU",
	date => "September 10, 2015"),
array(name => "Kay Chernush '66",
	text => "<p><strong>Kay Chernush '66</strong> announced that her organization, ArtWorks for Freedom launched its <a href=\"http://www.artworksforfreedom.org/\" target=\"_blank\">new web site</a>, with a new display of their arts portfolio and a new emphasis on storytelling through their blog. ArtWorks for Freedom is commited to building widespread public awareness of human trafficking and modern slavery, and inspiring creative action toward its eradication.</p>",
	url => "http://www.artworksforfreedom.org/",
	date => "September 10, 2015"),
array(name => "Meredith Monk '64",
	text => "<p><strong>Meredith Monk '64</strong> will be among the recipients of the 2014 National Medal of Arts and National Humanities Medal today for her \"contributions as a composer, singer, and performer. Renowned for her groundbreaking vocal techniques, Ms. Monk has reimagined the instrument of voice with her innovative work.\" See <a href=\"http://www.whitehouse.gov/the-press-office/2015/09/04/advisory-president-obama-award-2014-national-medal-arts-and-national%20\" target=\"_blank\">whitehouse.gov</a> for more information.</p>",
	date => "September 10, 2015"),
array(name => "Kate Scelsa '02",
	text => "<p><strong>Kate Scelsa '02</strong> announced the publication of her debut novel, <em>Fans of the Impossible Life</em>, on September 9, 2015. It's been chosen as an American Booksellers Association Indies Introduce Fall Pick and just got a starred review in <a href=\"http://publishersweekly.com/978-0-06-233175-5\" target=\"_blank\">Publishers Weekly</a>. The book is available for pre-order at <a href=\"http://www.amazon.com/dp/0062331752/ref=cm_sw_su_dp\" target=\"_blank\">Amazon</a>.</p>",
	url => "http://publishersweekly.com/978-0-06-233175-5",
	date => "September 9, 2015"),
array(name => "Laurie Blauner '75",
	text => "<p><strong>Laurie Blauner '75</strong> is winner of the 2015 Leapfrog Fiction Contest and her novel called <em>The Solace of Monsters</em> will be published in Fall 2016. See <a href=\"http://www.leapfrogpress.com\" target=\"_blank\">leapfrogpress.com</a> for more information.</p>",
	url => "http://www.leapfrogpress.com",
	date => "September 9, 2015"),
array(name => "Joelle Wallach '67",
	text => "<p>Composer <strong>Joelle Wallach '67</strong> has just completed <em>Summer Suite</em>, a new work for piano 4-hands, commissioned for Octavia, the piano ensemble of Meredith College in Raleigh, N. Carolina. The World Premiere will be given on February 19, 2016.</p>",
	date => "September 9, 2015"),
array(name => "Joelle Wallach '67",
	text => "<p><strong>Joelle Wallach '67</strong> will be speaking 14 times this Fall as part of the New York Philharmonic Insights Pre-Concert Lectures series. November 4, 5, 6 and 7 - Mozart in Vienna, November 11, 12, 13, 14 and 17 - Rachmaninoff: Melancholy &amp; Marchand's, December 15, 16, 17, 18 and 19 - Handel's Miraculous Messiah. More about these and her other upcoming lectures at<a href=\"http://joellewallach.com/current-season/lectures-broadcast/\" target=\"_blank\">http://joellewallach.com/current-season/lectures-broadcast/.<br></a> </p>",
	url => "http://joellewallach.com/current-season/lectures-broadcast/",
	date => "September 9, 2015"),
array(name => "Robert Ivey MFA '08",
	text => "<p><strong>Robert Ivey MFA '08</strong> announced that his chapbook, <em>Letters to My Daughter</em>, is being published by Blue Lyra Review on February 15, 2016. It will be featured in Vol. 1 of the Delphi Series of books. <a href=\"http://www.bluelyrareview.com%20\" target=\"_blank\">Blue Lyra Review</a> will sell the book on kindle and in print and at Association of Writers and Writing Programs. The book will contain three chapbooks by three authors: Robert Ivey, Anna Leahy, and Karen George.</p>",
	date => "September 8, 2015"),
array(name => "Alexandra Davin '98",
	text => "<p><strong>Alexandra Davin '98</strong> will be offering a therapeutic drama group for support and personal growth through creative play, this September on Friday mornings. Using theater, movement, music, and art as tools, the class will build a supportive environment to explore uncertainy and to promote positive change. Sessions are 90 minutes long weekly and run for eight weeks. The location is in midtown Manhattan and the cost is $350. For more information, please email&nbsp;<a href=\"mailto:alexandra.devin@gmail.com\">alexandra.devin@gmail.com</a>.<a></a></p>",
	date => "September 8, 2015"),
array(name => "Cynthia Bardes '63",
	text => "<p><em>Pansy in the Palace</em> by <strong>Cynthia Bardes '63</strong> (the first in what is now a series of children's books featuring the adventurous brown poodle and a young girl named Avery) has been adapted into a musical called Poodleful! Presented by Riverside Theatre (3250 Riverside Park Dr, Vero Beach, Florida), the show is “Broadway ready” and debuts with performances September 18-20. Tickets are available at Riverside box office or <a href=\"http://riversidetheatre.com/1516/Poodleful/\" target=\"_blank\">online</a>.</p>",
	url => "http://riversidetheatre.com/1516/Poodleful/",
	date => "September 4, 2015"),
array(name => "Amanda Foreman ‘91",
	text => "<p>The Ascent of Woman is a landmark four-part documentary series for BBC Two written and presented by <strong>Amanda Foreman ‘91</strong> that charts the role of women in society over the course of 10,000 years. Amanda argues that the history of women isn't a straight line from Eve's apple to Margaret Sanger's Pill. Over the past ten thousand years it has veered wildly between extremes of freedom and oppression, inclusion and exclusion. The Ascent of Woman starts 2nd September on BBC Two at 9pm.</p>",
	date => "September 2, 2015"),
array(name => "Judson Simmons MFA '04",
	text => "<p><strong>Judson Simmons MFA '04</strong> announced that his new chapbook, \"Sparrow, Sparrow\", will be published by Finishing Line Press this September. See <a href=\"http://finishinglinepress.com/product_info.php?\" target=\"_blank\">the Finishing Lines Press web site</a> for more information.</p>",
	url => "http://finishinglinepress.com/product_info.php?",
	date => "September 1, 2015"),
array(name => "Jeffrey McDaniel '90",
	text => "<p><strong>Jeffrey McDaniel '90</strong> will be reading at The Ugly Mug Cafe in Orange on Wednesday, August 26th at 8 pm, $3 cover.</p>",
	date => "August 25, 2015"),
array(name => "Carol Zoref '76, MFA '97",
	text => "<p><strong>Carol Zoref '76, MFA '97</strong> has won the 2015 AWP Award Series for the Novel for <em>Barren Island</em> (New Issues Press). Judge Paul Harding said: \"Barren Island is a wonderful synthesis of character and history… the author immerses us in a world most readers would never otherwise have known existed.”</p>",
	date => "August 25, 2015"),
array(name => "Leah Umansky MFA ‘04",
	text => "<p><strong>Leah Umansky MFA ‘04</strong> will make her Chicago debut with a <a href=\"http://www.facebook.com/events/1654141131464650/\" target=\"_blank\">poetry reading</a> later this summer.</p>",
	url => "http://www.facebook.com/events/1654141131464650/",
	date => "August 20, 2015"),
array(name => "David Schiller '66",
	text => "<p><strong>David Schiller '66</strong> announced the revised version of his two-volume translation and study of Confucius' Analects entitled, <em>CONFUCIUS: Discussions/Conversations</em> or, the Analects [Lun-yu]. <a href=\"http://www.amazon.com/CONFUCIUS-Discussions-Conversations-Analects-Lun-yu/dp/0981748317/ref=pd_bxgy_14_img_y\" target=\"_blank\">Volume I</a> and <a href=\"http://www.amazon.com/CONFUCIUS-Discussions-Conversations-Analects-Lun-yu/dp/0981748325/ref=pd_bxgy_14_img_y\" target=\"_blank\">Volume II</a>&nbsp;are now available for sale on Amazon. Included with the translation are a short history of early China, a short biography of Confucius, extensive summaries of the important commentaries from early Chinese philosophers, chronologies of dynasties and personages, and a concordance of key Chinese characters (both with original characters and transliterations) used in the text.</p>",
	url => "http://www.amazon.com/CONFUCIUS-Discussions-Conversations-Analects-Lun-yu/dp/0981748317/ref=pd_bxgy_14_img_y",
	date => "August 19, 2015"),
array(name => "Jesse Heffler MFA '13 and Vinny Mraz MFA '15",
	text => "<p><em>Win for Life: A Corny Play</em> is playing now at The New York International Fringe Festival. Directed by faculty member Kevin Confoy (and written by his daughter Quincy, a long ago alum of the ECC), it features the talents of Sound Designer <strong>Jesse Heffler MFA '13, Assistant Director Vinny Mraz MFA '15,</strong> and Production Assistant <strong>Claribel Gross MFA '16</strong>.</p><p>Remaining performances will be Friday, 8/21 (9 pm), Sunday, 8/23 (12:15 pm), and Thursday, 8/27 (4:30 pm) at The Celebration of Whimsy Theater. <a href=\"http://www.winforlifenyc.com/\" target=\"_blank\">http://www.winforlifenyc.com/</a></p>",
	url => "http://www.winforlifenyc.com/",
	date => "August 19, 2015"),
array(name => "Nicole Grabow '95",
	text => "<p><strong>Nicole Grabow '95</strong> will a public lecture on Art Conservation at the Des Moines Art Center. Have you ever wondered what happens when artwork is damaged? How does the passage of time affect sculpture? What issues are considered when conserving priceless artworks? Did you know that artist David Smith sometimes did his own touch-up painting or that Henry Moore's bronze sculpture was once rolled down a hill? Nicole Grabow, who has worked to repair and conserve several Art Center sculptures in the last year will share images, research, and stories in this fascinating behind-the-scenes glimpse of art conservation at the Des Moines Art Center.</p><p>For more information, see:<a href=\"http://www.desmoinesartcenter.org/aspx/events/event-detail.aspx?%20eventID=19836\" target=\"_blank\">http://www.desmoinesartcenter.org/aspx/events/event-detail.aspx? eventID=19836</a> </p>",
	date => "August 15, 2015"),
array(name => "Kate Scelsa '02",
	text => "<p>The upcoming <em>Fans of the Impossible Life</em> by <strong>Kate Scelsa '02</strong> was included in a discussion in the <em><a href=\"http://www.nydailynews.com/entertainment/theater-arts/young-adult-books-feature-threesomes-article-1.2321539?cid=bitly\" target=\"_blank\">NY Daily News</a><em>.</em></em> </p>",
	url => "http://www.nydailynews.com/entertainment/theater-arts/young-adult-books-feature-threesomes-article-1.2321539?cid=bitly",
	date => "August 12, 2015"),
array(name => "Stephanie R. Cooper '65, MFA '76",
	text => "<p><strong>Stephanie R. Cooper '65, MFA '76</strong> featured in the <a href=\"http://www.nytimes.com/2015/08/11/nyregion/when-tenants-cant-be-\" target=\"_blank\"><em>New York Times</em></a> fighting a new kind of vertical development on the UWS.</p>",
	url => "http://www.nytimes.com/2015/08/11/nyregion/when-tenants-cant-be-",
	date => "August 12, 2015"),
array(name => "Rhona Free '78",
	text => "<p><strong>Rhona Free '78</strong>, became president of the University of Saint Joseph on July 1, 2015.</p><p class=\"right\"><img align=\"right\" alt=\"Stone River Sky - book cover\" src=\"http://alum.slc.edu/image/news-15---16/StoneRiverSky_bookcover.jpg\"></p>",
	date => "August 7, 2015"),
array(name => "Robert Perry Ivey's '08",
	text => "<p>\"To Home,\" a poem by <strong>Robert Perry Ivey's '08</strong>,&nbsp;which was first published in <em>Lumina</em>, has been selected for publication in Negative Capability Press's <em>Stone, River, Sky: Anthology of Georgia Poems</em>. The anthology features Sarah Lawrence's Thomas Lux as well as current Poet Laureate Natasha Trethewey and former president Jimmy Carter. It is available on <a href=\"http://www.amazon.com/Stone-River-Sky-Anthology-Georgia/dp/0942544226/ref=sr_1_1?s=books&amp;ie=UTF8&amp;qid=1438972023&amp;sr=1-1&amp;keywords=Stone+River+Sky\" target=\"_blank\">Amazon</a>.</p>",
	url => "http://www.amazon.com/Stone-River-Sky-Anthology-Georgia/dp/0942544226/ref=sr_1_1?s=books&amp;ie=UTF8&amp;qid=1438972023&amp;sr=1-1&amp;keywords=Stone+River+Sky",
	date => "August 7, 2015"),
array(name => "Kaui Hart Hemmings MFA '02",
	text => "<p><strong>Kaui Hart Hemmings MFA '02</strong> announced that her first young adult novel, <em>JUNIORS</em>, will be published by Penguin Putnam September 2015. It is available for pre-order on <a href=\"http://www.amazon.com/Juniors-Kaui-Hart-Hemmings/dp/0399173609/ref=pd_sim_14_2?ie=UTF8&amp;refRID=0BXREV7RC3APJJKABRAAhttp://\" target=\"_blank\">Amazon</a>.</p>",
	url => "http://www.amazon.com/Juniors-Kaui-Hart-Hemmings/dp/0399173609/ref=pd_sim_14_2?ie=UTF8&amp;refRID=0BXREV7RC3APJJKABRAAhttp://",
	date => "August 7, 2015"),
array(name => "Melissa Crowe MFA '99",
	text => "<p>After serving as a member of the editorial board for five years, <strong>Melissa Crowe MFA '99</strong> has been named co-editor, with Rachel Contreni Flynn, of <em>Beloit Poetry Journal</em>.</p>",
	date => "August 7, 2015"),
array(name => "Michael Leong MFA '03",
	text => "<p><strong>Michael Leong MFA '03</strong> received a 2016 Literature Translation Fellowship from the National Endowment for the Arts to translate, with Ignacio Infante, the avant-garde Chilean poet Vicente Huidobro.</p>",
	date => "August 7, 2015"),
array(name => "Carolyn Newberger '63",
	text => "<p><strong>Carolyn Newberger '63</strong> has been illustrating her husband Eli Newberger's performance reviews for <em>The Berkshire Edge</em>. She says, \"It's been fun and challenging, drawing in real time, in the dark, during performances.\" <a href=\"http://theberkshireedge.com/at-tanglewood-paul-lewis-emerson-string-quartet-extol-beethovens-final-works-it-must-be/\" target=\"_blank\">Check out her latest illustrations and find more throughout the website</a>.</p>",
	url => "http://theberkshireedge.com/at-tanglewood-paul-lewis-emerson-string-quartet-extol-beethovens-final-works-it-must-be/",
	date => "August 1, 2015"),
array(name => "Chelsea Catalanotto '12",
	text => "<p><strong>Chelsea Catalanotto '12</strong> was recently awarded an official selection for her film \"Someone Else\" which was selected out of 1000+ global entrants, to screen at the prestigious Los Angeles Lift-Off Film Festival, an indie event held annually in Hollywood.</p>",
	date => "August 1, 2015")
];
?>