
$(function() {

  // $('body').append('<iframe name="result" id="result" style="position:fixed; bottom:0; right:0; width:50%; background:#fff; transition:height .35s;"></iframe><div class="btn btn-info" id="iframe-expander" style="position:fixed; bottom:0; right:50%;">Expand Results</div>');
  // $('#iframe-expander').click(function() { $('#result').toggleClass('bigger'); });

  $('.event-form .collapser').click(function() {
    $(this).closest('.event-form').find('.event-details').slideToggle().parent().find('.btn-group').slideToggle()
  });

  String.prototype.capitalize = function() {
    return this.charAt(0).toUpperCase() + this.slice(1);
  }

  function selectizeOptions(arr) {
    options = [];
    $.each(arr, function(i,v) {
      options.push({text: v, value: v});
    });
    return options;
  }
  function selectItems(t) {
    items = [];
    if (t === 'channels') {items.push('WWW')}
    return items;
  }

  $('.event-form').each(function(i,v) {
    var id = $(this).data('id');
    window['selectize'+id] = [];
    $.each(types, function(i,t) {
      var inputID = 'sel-'+t+'-'+id;
      $(v).find('.event-tags').append('<div class="tag-section"><label for="'+inputID+ '">'+ t.capitalize() +'</label><input id="'+inputID+ '" name="'+ t +'" type="text"></div>');
      window['selectize'+id][i] = $('#'+inputID).selectize({
        delimiter: ";",
        options: selectizeOptions(window[t]),
        placeholder: t.capitalize(),
        items: selectItems(t),
        maxItems: t === "faculty" ? 1 : null
      });
    });

    $('#deleted_events').clone().removeAttr('id').wrap('<div class="tag-section deleted-events"/>').parent().appendTo( $(this).find('.event-details') ); 
    $(this).find('.deleted-events').append('<input type="submit" name="submit" class="btn btn-info btn-copy btn-action" value="Copy data"/>'); 
    $(this).find('.deleted-events select').selectize();

    $(this).find('.loading-tagging').remove();

    $('.event-actions').removeClass('hidden');
  });
  $('#deleted_events').remove();

  $('.event-form .btn-enable').click(function(e) {
    if ( $(this).is('.disabled') ) { e.preventDefault(); return false; }
    $(this).closest('form').attr('action','enable.php?year=' + window.eventYear);
    $(this).closest('form').find('h5').append('<div class="label label-success">Enable request sent</div>');
    $(this).closest('form').find('.btn-action').addClass('disabled');
    $(this).closest('form').find('.event-actions, .deleted-events').hide();
    id = $(this).closest('form').data('id');
    selectizedFormInputs = window['selectize'+id];
    if (typeof selectizedFormInputs !== 'undefined' && Array.isArray(selectizedFormInputs) ) {
      $.each(selectizedFormInputs, function() {
        this[0].selectize.lock();
      });
    }
  });
  $('.event-form .btn-reject').click(function(e) {
    if ( $(this).is('.disabled') ) { e.preventDefault(); return false; }
    $(this).closest('form').attr('action','reject.php?year=' + window.eventYear);
    $(this).closest('form').find('h5').append('<div class="label label-important">Reject request sent</div>');
    $(this).closest('form').find('.btn-action').addClass('disabled');
    $(this).closest('form').find('.event-actions, .event-tags, .deleted-events').hide();
  });
  $('.event-form .btn-copy').click(function(e) {
    if ( $(this).is('.disabled') ) { e.preventDefault(); return false; }
    $(this).closest('form').attr('action','copyData.php?year=' + window.eventYear);
    $(this).closest('form').find('h5').append('<div class="label label-info">Copy request sent</div>');
    $(this).closest('form').find('.btn-action').addClass('disabled');
    $(this).closest('form').find('.event-actions, .event-tags').hide();
  });

});


window.types = [
  "academics",
  "audiences",
  "themes",
  "sponsors",
  "channels",
  "faculty"
];
window.academics = [
  "Humanities",
  "History and the Social Sciences",
  "Science and Mathematics",
  "Creative and Performing Arts",
  "Africana Studies",
  "Anthropology",
  "Art History",
  "Asian Studies",
  "Biology",
  "Chemistry",
  "Chinese",
  "Classics",
  "Cognitive and Brain Science",
  "Computer Science",
  "Dance",
  "Design Studies",
  "Development Studies",
  "Economics",
  "Environmental Studies",
  "Ethnic and Diasporic Studies",
  "Film History",
  "French",
  "Games, Interactive Art, and New Genres",
  "Gender and Sexuality Studies",
  "Geography",
  "German",
  "Greek",
  "Health, Science, and Society",
  "History",
  "International Studies",
  "Italian",
  "Japanese",
  "Latin",
  "Latin American and Latino/a Studies",
  "LGBT",
  "Literature",
  "Mathematics",
  "Middle Eastern and Islamic Studies",
  "Modern Languages and Literatures",
  "Music",
  "Philosophy",
  "Physics",
  "Political Economy",
  "Politics",
  "Pre-med",
  "Psychology",
  "Public Policy",
  "Religion",
  "Russian",
  "Science, Technology, and Society",
  "Sociology",
  "Spanish",
  "Theatre",
  "Urban Studies",
  "Visual and Studio Arts",
  "Digital Imagery",
  "Drawing",
  "Filmmaking and Moving Image Arts",
  "Painting",
  "Photography",
  "Printmaking",
  "Sculpture",
  "Women’s Studies",
  "Writing",
  "Art of Teaching",
  "Child Development",
  "MFA Dance",
  "Dance Movement Therapy",
  "Health Advocacy",
  "Human Genetics",
  "MFA Theatre",
  "Womens History",
  "MFA Writing",
  "Continuing Education",
  "Child Development Institute",
  "Early Childhood Center",
  "Special Programs",
  "Study Abroad",
  "Writing Institute"
];
window.audiences = [
  "Administration",
  "Alumni",
  "Cristle Collins Judd",
  "Donors",
  "Faculty",
  "Friends of the College",
  "Graduate",
  "High School",
  "Karen R. Lawrence",
  "Neighbors",
  "Parents",
  "President",
  "Public",
  "Staff",
  "Students",
  "Undergraduate"
];
window.themes = [
  "Academics",
  "Advancement",
  "Athletics",
  "BWCC",
  "Careers",
  "Commencement",
  "Graduate Admission",
  "Inauguration",
  "Library",
  "NYC and Local",
  "Reunion",
  "Student Life",
  "Undergraduate Admission"
];
window.sponsors = [
  "Alumni Relations",
  "Career Services",
  "DAPS",
  "Real Talk",
  "SLAC"
];
window.channels = [
  "WWW",
  "Homepage",
  "InTouch",
  "CURB"
]
window.faculty = [
  "abernethy-colin-d.",
  "abraham-julie",
  "abrams-samuel",
  "abuba-ernest-h.",
  "acting-faculty-",
  "adams-jefferson",
  "afzal-cameron-c.",
  "agard-jones-vanessa",
  "aggarwal-ujju",
  "agresta-kirsten",
  "alan-gilbert",
  "albarelli-gerry",
  "alexander-glenn",
  "alexis-melissa",
  "algire-andrew",
  "ancona-marina",
  "anderson-abraham",
  "anderson-william",
  "andriole-stephanie",
  "anhalt-emily-katz",
  "appel-cathy",
  "arditi-neil",
  "ash-erin",
  "bajaj-komal",
  "baker-damani",
  "baker-nancy",
  "balasubramaniam-tanjore",
  "balkite-elisabeth-a.",
  "barenboim-carl",
  "barenboim-deanna",
  "barnard-mary",
  "basilio-jorge",
  "beard-jo-ann",
  "beavan-colin",
  "begelman-igor",
  "belcastro-sarah-marie",
  "benzoni-stefania",
  "berg-bruce",
  "bernstein-david",
  "biscardi-chester",
  "blake-lorna-knowles",
  "blalock-lucas",
  "bosselaar-laure-anne",
  "bower-bill-l.",
  "bradshaw-patti",
  "brand-roy",
  "breitbart-vicki",
  "brodzki-bella",
  "brown-adam",
  "brown-karen",
  "brown-kurt",
  "brown-wesley",
  "buckley-jennifer",
  "bukiet-melvin-jules",
  "burnley-gary",
  "calvin-scott",
  "canick-jacob",
  "carbon-lorayne",
  "carstens-marie",
  "carter-suzanne",
  "castillo-mauricio",
  "castriota-david",
  "catanzaro-william",
  "catterson-pat",
  "chang-tina",
  "chapman-susannah",
  "charles-persis",
  "cheng-eileen-ka-may",
  "chen-mengyu",
  "chen-priscilla",
  "cho-john-song-pae",
  "christle-heather",
  "chung-una",
  "clark-sarah",
  "cleary-heather",
  "cohen-rachel",
  "confoy-kevin",
  "conlan-kelli",
  "corva-dominic",
  "cottrell-margaret",
  "cottrell-peggy",
  "cramer-michael",
  "cressman-drew-e.",
  "cruz-cynthia",
  "curulla-annelle",
  "dance-faculty-",
  "dasgupta-sayantani",
  "datta-rhea",
  "davis-michael",
  "de-leon-cora",
  "delne-claudy",
  "de-sena-isabel",
  "desjarlais-robert-r.",
  "devine-emily",
  "diamond-david",
  "dillard-mary",
  "ditkoff-beth-ann",
  "dixon-jonathan",
  "dizenko-natalia",
  "dobyns-stephen",
  "dodds-jerrilynn",
  "dolan-siobhan",
  "dollinger-roland",
  "donzelli-aurora",
  "downs-patrick",
  "doyle-charlotte-l.",
  "driscoll-kermit",
  "drucker-jan",
  "du-boff-jill",
  "duce-scott",
  "dufresne-angela",
  "duggan-niamh",
  "dumbutshena-rujeko",
  "duran-nancy",
  "durcan-judith",
  "dynner-glenn",
  "earle-jason",
  "early-michael",
  "eger-david-j.",
  "ekman-june",
  "ellicson-kirsten",
  "ellis-matthew",
  "ellis-thomas-sayers",
  "emmons-beverly",
  "escobar-chaparro-gloria",
  "faculty-design",
  "faculty-music",
  "fader-oren",
  "fagan-charling-c.",
  "fajardo-margarita",
  "farrell-christine",
  "febos-melissa",
  "ferguson-kim",
  "ferraiolo-angela",
  "ferrell-carolyn",
  "folkman-marjorie",
  "forbes-barbara",
  "forte-joseph-c.",
  "foulk-t.-griffith",
  "frankel-marvin",
  "frazier-melissa",
  "frears-will",
  "friedman-donald",
  "fuchs-marek",
  "gabaston-liza",
  "garcia-laura",
  "gardinier-suzanne",
  "gay-jackson",
  "germano-roy",
  "gessen-keith",
  "gillis-graeme",
  "gilvary-sara",
  "goldberg-myra",
  "goldman-nina",
  "goldray-martin",
  "gorn-cindy",
  "gould-peggy",
  "greb-anne",
  "greenberg-michael",
  "greenwald-maggie",
  "grewal-gwenda-lin",
  "griepp-eva-bostein",
  "griffiths-rachel-eliza",
  "grob-rachel-n.",
  "gross-susan",
  "guest-artists-",
  "guests-",
  "gustafson-barret-charlie",
  "hallberg-garth-risk",
  "handy-catherine",
  "hansen-anneke",
  "hardy-dave",
  "harris-hilda",
  "harvey-matthea",
  "hassan-sarah",
  "hebron-mary",
  "helias-mark",
  "henkin-joshua",
  "heppermann-ann",
  "herb-alice",
  "hercher-laura",
  "heredia-luisa-laura",
  "herships-sally",
  "hersh-michelle",
  "higgins-niko",
  "hill-kathleen",
  "hoch-james",
  "hollander-david",
  "hong-cathy-park",
  "hoover-suzanne-r.",
  "horowitz-james",
  "howell-fanon",
  "howe-marie",
  "hsu-tishan",
  "hultman-iréne",
  "human-genetics-faculty-",
  "humbaugh-erin",
  "hurlin-dan",
  "hwang-koosil-ja",
  "hyman-yehuda",
  "iacoboni-daniel",
  "iliatova-vera",
  "index",
  "index.xml",
  "ingliss-robert",
  "jablonski-meghan",
  "jacques-lmsw-christobal--j.",
  "james-tara-elise",
  "jansma-kristopher",
  "jeter-james",
  "johnson-daniel",
  "johnson-kate-knapp",
  "johnson-rebecca-o.",
  "johnston-elizabeth",
  "jones-alwin-a.-d.",
  "jones-brian",
  "kahler-jean",
  "kaplan-shirley",
  "kart-susan",
  "katz-kuniko",
  "kaufmann-kathy",
  "kelley-william-melvin",
  "kelly-deborah",
  "kempson-sibyl",
  "kerekes-paul",
  "ketchum-barbara-bray",
  "khakpour-porochista",
  "kilroy-marac-kathleen",
  "king-daniel",
  "king-jonathan",
  "kirsch-adam",
  "klass-david",
  "klinkenborg-verlyn",
  "korsunskaia-ekaterina",
  "kreider-timothy",
  "kronn-david",
  "krugman-jason",
  "krupat-arnold",
  "kurland-justine",
  "kyle-peter",
  "lachapelle-mary",
  "lago-eduardo",
  "landdeck-kevin",
  "lang-allen",
  "lauinger-ann",
  "lauinger-joseph",
  "lavigne-sharon",
  "lawrence-karen-r.",
  "lee-michelle",
  "lee-tom",
  "leonelli-laurie-beth",
  "leveau-eric",
  "lewis-linwood-j.",
  "lewis-margot",
  "lieber-caroline",
  "lieberman-sandy",
  "lieu-jocelyn",
  "lin-tao",
  "liu-wan-chun",
  "liu-wen",
  "long-laura-i.",
  "lux-thomas",
  "lyons-robert",
  "machugh-doug",
  "macías-patrisia",
  "macmillan-brian",
  "macpherson-greg",
  "magnuson-robert",
  "maillo-pozo-ruben",
  "manago-alexander-merceditas",
  "mañago-alexander-merceditas",
  "mandel-thomas",
  "mark-rona-naomi",
  "marshall-james",
  "martinez-deluca-margaret",
  "matthews-amy",
  "may-juliana",
  "mazmanian-victor",
  "mccarthy-janelle",
  "mcdaniel-jeffrey",
  "mcfarland-stephen",
  "mcghee-elena",
  "mcguire-liz",
  "mcintyre-dianne",
  "mcpherson-elizabeth",
  "mcree-william-d.",
  "means-angelia",
  "medley-cassandra",
  "meira-la",
  "melnick-jodi-melnick",
  "miller-jeffrey",
  "miller-timothy",
  "mills-joseph",
  "mills-nicolaus",
  "minsky-greta",
  "misra-lavanya",
  "mitchell-rashaun",
  "mizelle-nike",
  "mizrahi-terry",
  "moe-ruth",
  "mofidi-shideh",
  "moger-angela",
  "moos-katherine",
  "morejon-diana-punales",
  "morris-mary",
  "mort-bari",
  "morton-brian",
  "mosolino-april-reynolds",
  "moudud-jamee-k.",
  "muchmore-patrick",
  "muldavin-joshua",
  "murolo-priscilla",
  "murray-katie",
  "muther-catherine",
  "naka-cheiko",
  "naka-chieko",
  "neely-evan",
  "negroni-maria",
  "neskar-ellen",
  "neumann-david",
  "newhouse-erica",
  "newman-leigh",
  "nolin-sally",
  "novas-julie",
  "nurkse-dennis",
  "oconnor-john",
  "oconnor-stephen",
  "offill-jenny",
  "olson-leah",
  "ording-philip",
  "orlandersmith-dael",
  "ornstein-sloan-magdalena",
  "oshea-marygrace",
  "oyama-sayuri-i.",
  "oziashvili-yekaterina",
  "paramaditha-intan",
  "parker-matthew",
  "partin-ted",
  "pearce-nicole",
  "peixoto-michael",
  "pelletier-carol-ann",
  "peritz-david",
  "petty-lauren",
  "pfordresher-jeanne1",
  "philipps-kris",
  "philogene-gina",
  "pierce-young-eddye",
  "pilkington-kevin",
  "pollack-maika",
  "pollak-max",
  "porter-karen",
  "porter-mary-a.",
  "power-marilyn",
  "prieto-josé-manuel",
  "rainer-yvonne",
  "raja-kanishka",
  "rakoff-joanna-smith",
  "redel-victoria",
  "reich-elsa",
  "reifler-nelly",
  "reilly-janet",
  "reksten-nicholas",
  "rezai-hamid",
  "rhodes-martha",
  "richards-peter",
  "risher-elise",
  "rivera-colon-edgar",
  "robinson-sandra",
  "rodenbeck-judith",
  "rodgers-liz",
  "romano-patrick",
  "rorandelli-tristana",
  "rosenthal-lucy",
  "rouse-shahnaz",
  "rudner-sara",
  "ruen-kathleen",
  "ryan-david",
  "sampson-efeya-ifadayo-m",
  "sanborn-erica",
  "sanchez-misael",
  "sanders-wayne",
  "sands-kristin-zahra",
  "saptanyana-nyoman",
  "saxon-la-rose",
  "schachter-amanda",
  "schecter-barbara",
  "scheier-fanchon-miller",
  "schlesinger-mark-j.",
  "schmidt-carsten",
  "schneider-ursula",
  "schorsch-jonathan",
  "schrader-astrid",
  "schultz-anthony",
  "schultz-tony",
  "scotch-marmo-malia",
  "sealander-rebecca",
  "seibel-jean",
  "seigle-samuel-b.",
  "serafini-sauli-judith-p.",
  "seshadri-vijay",
  "shafer-susan-h.",
  "shemy-deganit",
  "sherman-maxine",
  "shuford-gabriel",
  "shullenberger-william",
  "shulman-mark-r.",
  "siff-michael",
  "silber-joan",
  "simons-lake",
  "singh-kanwal",
  "singh-paul",
  "sivesind-david",
  "sizer-lyde-cullen",
  "slichter-jacob",
  "smith-michael-j.",
  "smoler-fredric",
  "snead-pamela",
  "sohn-sungrai",
  "soiseth-alexandra",
  "sosnowy-collette",
  "southgate-martha",
  "spano-michael",
  "speer-james-w.",
  "speight-rico",
  "spencer-stuart",
  "starbuck-robin",
  "sternfeld-joel",
  "stevens-brooke",
  "strype-frederick-michael",
  "swann-sterling",
  "swoboda-philip",
  "tba-faculty",
  "technical-staff-",
  "thomas-nadeen-m.",
  "thom-rose-anne",
  "thurber-lucy",
  "to-be-announced-",
  "tomasulo-frank",
  "truax-alice",
  "turvey-malcolm",
  "ulmert-megan",
  "uttley-lois",
  "vahrenwald-michael",
  "vasudevan-preeti",
  "vesely-flad-rima",
  "vincenot-dash-stella",
  "vitkin-marina",
  "voice-faculty-",
  "volpe-francine",
  "wachs-ilja",
  "weil-laura",
  "weis-cathy",
  "weiss-heidi",
  "wentworth-jean",
  "weschler-lawrence",
  "westwater-kathy",
  "wiersma-cal",
  "wilbur-jennifer-scalia",
  "wilcox-sarah",
  "wilford-sara",
  "wilson-fiona",
  "wilson-matthew",
  "winter-joe",
  "winters-heather",
  "woodard-komozi",
  "woolfson-joseph-w.",
  "wright-alexandra",
  "wunderlich-mark",
  "yamamoto-miyabi",
  "yang-min",
  "yannelli-john",
  "yates-jonathan",
  "yin-mali",
  "yionoulis-evan",
  "yoo-mia",
  "yoon-paul",
  "young-thomas",
  "zambreno-kate",
  "zerfas-francine",
  "zerner-charles",
  "zevin-dan",
  "zollar-keisha",
  "zoref-carol",
  "zuern-elke"
]
